// db connection related
export const DB_MAX_RETRIES = 3;
export const DB_RETRY_INTERVAL = 5000; // 5 seconds

export const UserRolesEnum = {
  ADMIN: "ADMIN",
  STUDENT: "STUDENT",
  INSTRUCTOR: "INSTRUCTOR",
};

export const CourseCatogoriesEnum = {
  DEVELOPMENT: "DEVELOPMENT",
  BUSINESS: "BUSINESS",
  FINANCE_ACCOUNTING: "FINANCE_ACCOUNTING",
  IT_SOFTWARE: "IT_SOFTWARE",
  OFFICE_PRODUCTIVITY: "OFFICE_PRODUCTIVITY",
  PERSONAL_DEVELOPMENT: "PERSONAL_DEVELOPMENT",
  DESIGN: "DESIGN",
  MARKETING: "MARKETING",
  LIFESTYLE: "LIFESTYLE",
  PHOTOGRAPHY_VIDEO: "PHOTOGRAPHY_VIDEO",
  HEALTH_FITNESS: "HEALTH_FITNESS",
  MUSIC: "MUSIC",
  TEACHING_ACADEMICS: "TEACHING_ACADEMICS",
  LANGUAGE_LEARNING: "LANGUAGE_LEARNING",
  ENTREPRENEURSHIP: "ENTREPRENEURSHIP",
  ARTS_CRAFTS: "ARTS_CRAFTS",
  COOKING_BAKING: "COOKING_BAKING",
  MENTAL_HEALTH: "MENTAL_HEALTH",
  SCIENCE_TECHNOLOGY: "SCIENCE_TECHNOLOGY",
  TEST_PREPARATION: "TEST_PREPARATION",
  UNKNOWN: "UNKNOWN",
};

export const CourseLevelEnum = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  ADVANCED: "ADVANCED",
};

export const CoursePurchasePaymentEnum = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

export const RESET_PASSWORD_TOKEN_EXPIRY = 10 * 60 * 1000; // 10 minutes
